///
/// This file is auto generated by CMake from bibstd/res/scripture.cpp.in
/// Do not edit this file directly.
///
#include "bibstd/data/res_scripture.hpp"
#include "bibstd/util/incbin.hpp"

#include <array>
#include <span>

// clang-format off

namespace
{
const std::array<const std::byte*, 0> zip_data_ptrs = {};
const std::array<std::size_t, 0> zip_sizes = {};
} // anonymous namespace
namespace bibstd::data
{

///
///
auto zip_file_count() -> std::size_t
{
  return static_cast<std::size_t>(0);
}

// clang-format on
///
///
auto zip_file_raw(const std::size_t index) -> std::span<const std::byte>
{
  if(index >= zip_data_ptrs.size())
  {
    return {};
  }
  return {zip_data_ptrs.at(index), zip_sizes.at(index)};
}

} // namespace bibstd::data
