include(helper_functions)

#
# Copy setup files.
#
function(copy_target_files target dest mingw)
  # Copy needed *.dll's.
  copy_file(${target} "${dest}" "${mingw}/bin/libarchive-13.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libb2-1.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libboost_filesystem-mt.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libbrotlicommon.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libbrotlidec.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libbz2-1.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libcrypto-3-x64.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libcurl-4.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libdeflate.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libexpat-1.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libfmt-11.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libgcc_s_seh-1.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libgif-7.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libgomp-1.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libiconv-2.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libidn2-0.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libintl-8.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libjbig-0.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libjpeg-8.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libleptonica-6.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libLerc.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/liblz4.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/liblzma-5.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libnghttp2-14.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libnghttp3-9.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libopenjp2-7.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libpng16-16.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libpsl-5.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libsharpyuv-0.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libssh2-1.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libssl-3-x64.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libstdc++-6.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libtesseract-5.5.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libtiff-6.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libunistring-5.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libwebp-7.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libwebpmux-3.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libwinpthread-1.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/libzstd.dll")
  copy_file(${target} "${dest}" "${mingw}/bin/zlib1.dll")
  # Copy executable.
  copy_file(${target} "${dest}" "${CMAKE_CURRENT_BINARY_DIR}/${app_bible_workspace_EXE_NAME}.exe")
endfunction(copy_target_files)
