///
/// This file contains app version information.
/// This file is automatically generated. Do not modify!
///
#include <string_view>

constexpr unsigned int app_version_major_number = 1;
constexpr unsigned int app_version_minor_number = 0;
constexpr auto app_version_name = std::string_view("1.0");
